# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

alias nvim='sudo vim -u "NONE"'
alias vim='sudo -E vim'
alias vi='sudo -E vim'
alias gvim='sudo -E gvim'
alias fast='xset r rate 150 100'
alias subl='sublime'
alias svnu='sudo svn update'
alias svnci='sudo svn ci -m'
alias svna='sudo svn add'
alias svnl='sudo svn log'
alias svncu='sudo svn cleanup'
alias chmod777='sudo chmod 777 -R ./'
alias chmodx='sudo chmod +x'
alias svnup='cd ~ && ./update-svn.sh'
alias stats='cd ~/Dropbox/Jogue\ Free/Workflow/ && casperjs getStats.js'
alias tmux='tmux -c zsh'
alias gs='grunt server'
alias gd='grunt dist'
alias gdi='grunt dist:img'
alias gdj='grunt dist:js'
alias gdc='grunt dist:css'
alias gitl='git log --all --graph --decorate --oneline --abbrev-commit'
alias gits='git status -sb'
alias lst='ls -R | grep ":$" | sed -e '"'"'s/:$//'"'"' -e
'"'"'s/[^-][^\/]*\//--/g'"'"' -e '"'"'s/^/   /'"'"' -e '"'"'s/-/|/'"'"
alias dotFiles='cd ~/b0x/dotFiles/'
alias serve='python3 -m http.server'
alias dirsize='du -h --max-depth=1 "$@" | sort -k 1,1hr -k 2,2f'
alias :q='exit'
alias :Q='exit'
alias 'cd..'='cd ..'
alias npmi='sudo npm i'
alias bkp='sudo rsync -azP --rsh="ssh -p21" --exclude-from "$HOME/b0x/dotFiles/.ignore"'
alias energetico='cd ~/Dropbox/Jogue\ Free/boiada/ && bkp pv.txt cl.txt root@104.236.252.45:/home/boiada/ && bkp pv.txt cl.txt root@104.236.192.225:/home/boiada/'
alias pv="cd ~/Dropbox/Jogue\ Free/boiada/ && ./cron.sh pv 30 > /dev/null 2>&1&"
alias cl="cd ~/Dropbox/Jogue\ Free/boiada/ && ./cron.sh cl 30 > /dev/null 2>&1&"
alias parar="sudo kill -9 $(pgrep 'casperjs|cron.sh|phantomjs')"
alias sshcl='ssh -p 21 root@104.236.192.225'
alias sshboiada='ssh -p 21 root@104.236.252.45'
alias sshfranklin='ssh -p 21 site@franklinjavier.com'
alias sshsite='sudo ssh -p 21 site@45.55.86.140'
alias sshqueropontos='ssh -p 21 site@104.131.79.81'
alias _restart="sudo shutdown -r now"
alias _logout="sudo pkill -u $USER"
alias _shutdown="sudo shutdown -h now"
alias irc="irssi -c 172.22.98.219 -p 6667 -n franklin"
alias blog="cd ~/b0x/Projects/blog/"

# Sudo
alias s='sudo'

# CD
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ~='cd ~'

# RM
alias rm='rm -r -v'
alias rmf='rm -rf -v'

# CP
alias cp='cp -r'
alias cpp='rsync -PrlpE'
alias cpz='rsync -PrlpEz'

# LS
alias l='ls -Xp --color=auto'
alias ls='ls -Xp --color=auto'
alias ll='ls++'

# MKDIR
alias mk='mkdir -p -v'
alias mkdir='mkdir -p -v'

# Various
alias cls='clear'
alias h='history'

alias ps="ps aux"
alias pstree="pstree -au | grep"



# UOL
alias jsuol='cd ~/b0x/UOL/svn/webcontent/com/jsuol/c/'
alias info='cd ~/b0x/UOL/svn/branches/infograficos/'
alias tools='cd ~/b0x/UOL/tools/'
alias uol='cd ~/b0x/UOL/'
alias dataviz='cd ~/b0x/UOL/dataviz/'
alias tcl='sudo apache2ctl stop && cd ~/b0x/UOL/tcl/templatecache-local/ && sudo sh ./run.sh 80'
alias connect='cd ~/b0x/dotFiles/arch/ && sudo sh start.sh'
alias hosts='vim /etc/hosts'

export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=screen-256color

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/franklin/.rvm/bin'
# export MANPATH='/usr/local/man:$MANPATH'

# # Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='gvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"


precmd() { print "" }

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$PATH:$HOME/playframework/activator" # Add activator from Play framework

unset GREP_OPTIONS
source ~/.nvm/nvm.sh

#!/bin/sh
if [ "$TERM" = "linux" ]; then
  /bin/echo -e "
  \e]P01d1f21
  \e]P1cc6666
  \e]P2b5bd68
  \e]P3f0c674
  \e]P481a2be
  \e]P5b294bb
  \e]P68abeb7
  \e]P7c5c8c6
  \e]P8969896
  \e]P9cc6666
  \e]PAb5bd68
  \e]PBf0c674
  \e]PC81a2be
  \e]PDb294bb
  \e]PE8abeb7
  \e]PFffffff
  "
  # get rid of artifacts
  clear
fi

